### ISSUE TITLE
Cannot create Postgres migrations for `:money_with_currency`

### ISSUE THREAD

**Issue by ibarakaiev** [ash-project/ash_money#1]
Hi @zachdaniel, thank you for your work on this package!

I'm currently trying to install `AshMoney` and add `AshMoney.AshPostgresExtension` to the list of installed extensions for Postgres, and am facing some issues. Here are the steps I took to add it:

1. Add `{:ash_money, "~> 0.1.0"}` to `mix.exs`..
2. Add `AshMoney.AshPostgresExtension` to the end of the list inside `MyApp.Repo.installed_extensions/0`

That's it. Then, after running `mix ash_postgres.generate_migrations --name add_ash_postgres_money_extension`, I get the following error:

```elixir
Extension Migrations: 
** (UndefinedFunctionError) function Money.DDL.create_money_with_currency/0 is undefined (module Money.DDL is not available)
    Money.DDL.create_money_with_currency()
    (ash_money 0.1.0) lib/ash_money/ash_postgres_extension.ex:10: AshMoney.AshPostgresExtension.install/1
    (elixir 1.15.2) lib/enum.ex:1794: anonymous fn/2 in Enum.map_join/3
    (elixir 1.15.2) lib/enum.ex:4369: Enum.map_intersperse_list/3
    (elixir 1.15.2) lib/enum.ex:1794: Enum.map_join/3
    (ash_postgres 1.3.62) lib/migration_generator/migration_generator.ex:240: anonymous fn/2 in AshPostgres.MigrationGenerator.create_extension_migrations/2
    (elixir 1.15.2) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (ash_postgres 1.3.62) lib/migration_generator/migration_generator.ex:51: AshPostgres.MigrationGenerator.generate/2
```

The above is fixable by manually adding `ex_money_sql` to my `mix.exs`. But then, running the migration command again, I get:

```elixir
Extension Migrations: 
** (UndefinedFunctionError) function AshMoney.AshPostgresExtension.extension/0 is undefined (module AshMoney.AshPostgresExtension is not available)
    AshMoney.AshPostgresExtension.extension()
    (ash_postgres 1.3.63) lib/migration_generator/migration_generator.ex:187: anonymous fn/1 in AshPostgres.MigrationGenerator.create_extension_migrations/2
    (elixir 1.15.2) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (elixir 1.15.2) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (ash_postgres 1.3.63) lib/migration_generator/migration_generator.ex:185: anonymous fn/2 in AshPostgres.MigrationGenerator.create_extension_migrations/2
    (elixir 1.15.2) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (ash_postgres 1.3.63) lib/migration_generator/migration_generator.ex:51: AshPostgres.MigrationGenerator.generate/2
    (mix 1.15.2) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
```

and I'm not sure how to fix it this time. It appears from the source that loading `AshMoney.AshPostgresExtension` requires `AshPostgres.CustomExtension` to be loaded, but seems like that's not happening, and I'm not sure how to proceed here. Any pointers?

**Comment by zachdaniel** [comment]
Can you try doing `mix deps.compile ash_money --force`?

**Comment by ibarakaiev** [comment]
Unfortunately, that didn't fix it; exact same issue. I had originally tried it as well when I was trying to configure `:custom_types` per the getting started guide. For what it's worth, if I change a field in a schema, say `:price` from `:integer` to `:money`, then the autogenerated migration gets generated just fine, and the field gets modified to `:money_with_currency`, which I suppose won't work without the extension getting installed first. Here's my full `repo.ex`, in case it's helpful (it's very barebones):

```elixir
defmodule MyApp.Repo do
  use AshPostgres.Repo, otp_app: :my_app

  def installed_extensions do
    ["uuid-ossp", "citext", AshMoney.AshPostgresExtension]
  end
end
```

**Comment by zachdaniel** [comment]
Can you try the `main` branch? And also ensure you have `ex_money_sql` and `ash_postgres` deps in your `mix.exs`.

**Comment by zachdaniel** [comment]
And if that doesn't work, delete your `_build` directory and do a full compile.

**Comment by zachdaniel** [comment]
Must be a fix we added in a recent unreleased commit. I'll cut a new release.

**Comment by zachdaniel** [comment]
release 1.2
